refactor: move data under /symbios (LUKS overlay, new path variables)
- inventory.yml: data_root/git_root/base_services_root/services_root/docker_root/containerd_root/backup_root
- install.sh: clone repo to /symbios/git/SymbiOS, use new paths
- docker.yml: data-root via daemon.json + containerd config.toml instead of symlinks
- basics.yml: layout dirs, /home symlink, PATH, user home under data_root
- path updates in symbios-ui.yml/traefik/ldap/authelia/dedyn/backup/runchecks/autoupdate/smtp/ssh-keys
- symbios-home-partition.sh -> symbios-data-partition.sh: mounts /symbios, mapper symbios-luks, rsync incl. docker/containerd
- boot-unlock: unlock.py switched to /symbios, extract-le-cert reads from base_services_root
- WebUI: ssh_exec gateway to /symbios/git/SymbiOS, disk page to /symbios/data_*
- services/*.yml to /symbios/services/, README + docs updated

diff --git a/services/nextcloud.yml b/services/nextcloud.yml
--- a/services/nextcloud.yml
+++ b/services/nextcloud.yml
@@ -31,17 +31,17 @@
 #     services:
 #     - name: nextcloud
 #       type: docker
-#       compose_file: /home/docker/nextcloud/docker-compose.yml
-#       status: test -d /home/docker/nextcloud || exit 2; docker compose -f /home/docker/nextcloud/docker-compose.yml ps | grep -q "Up "
+#       compose_file: /symbios/services/nextcloud/docker-compose.yml
+#       status: test -d /symbios/services/nextcloud || exit 2; docker compose -f /symbios/services/nextcloud/docker-compose.yml ps | grep -q "Up "
 #     logs:
 #     - name: nextcloud
-#       command: docker compose -f /home/docker/nextcloud/docker-compose.yml logs -f --tail=100
+#       command: docker compose -f /symbios/services/nextcloud/docker-compose.yml logs -f --tail=100
 #   actions:
-#     uninstall: docker compose -f /home/docker/nextcloud/docker-compose.yml down
-#     start: docker compose -f /home/docker/nextcloud/docker-compose.yml up -d
-#     stop: docker compose -f /home/docker/nextcloud/docker-compose.yml down
-#     restart: docker compose -f /home/docker/nextcloud/docker-compose.yml restart
-#     reload: docker compose -f /home/docker/nextcloud/docker-compose.yml up -d
+#     uninstall: docker compose -f /symbios/services/nextcloud/docker-compose.yml down
+#     start: docker compose -f /symbios/services/nextcloud/docker-compose.yml up -d
+#     stop: docker compose -f /symbios/services/nextcloud/docker-compose.yml down
+#     restart: docker compose -f /symbios/services/nextcloud/docker-compose.yml restart
+#     reload: docker compose -f /symbios/services/nextcloud/docker-compose.yml up -d
 #
 
 ---
@@ -69,17 +69,17 @@
       ansible.builtin.set_fact:
         trusted_proxies_cidr: "{{ traefik_ip_result.stdout | regex_replace('^([0-9]+\\.[0-9]+\\.[0-9]+)\\..*$', '\\1.0/24') }}"
 
-    - name: Create /home/docker/nextcloud dir
+    - name: Create /symbios/services/nextcloud dir
       ansible.builtin.file:
-        path: /home/docker/nextcloud
+        path: /symbios/services/nextcloud
         owner: root
         group: docker
         state: directory
         mode: '0550'
 
-    - name: /home/docker/nextcloud/genpw.sh (generate Random PW for Nextcloud and DB)
+    - name: /symbios/services/nextcloud/genpw.sh (generate Random PW for Nextcloud and DB)
       blockinfile:
-        path: /home/docker/nextcloud/genpw.sh
+        path: /symbios/services/nextcloud/genpw.sh
         create: yes
         mode: 0550
         owner: root
@@ -87,7 +87,7 @@
         marker: "# {mark} ANSIBLE MANAGED BLOCK"
         block: |
           # Change to service directory
-          cd /home/docker/nextcloud
+          cd /symbios/services/nextcloud
 
           # Generate random passwords for Nextcloud admin and database
           g_ncadminpassword=$(pwgen -s 32 1)
@@ -128,21 +128,21 @@
         validate: /bin/bash -n %s
       notify: run genpw.sh
 
-    - name: /home/docker/nextcloud/genpw.sh shebang
+    - name: /symbios/services/nextcloud/genpw.sh shebang
       lineinfile:
-        path: /home/docker/nextcloud/genpw.sh
+        path: /symbios/services/nextcloud/genpw.sh
         insertbefore: BOF
         line: "#!/bin/bash -e"
 
     - name: Gen initial passwords if not exists
       ansible.builtin.shell: ./genpw.sh
       args:
-        chdir: /home/docker/nextcloud
-        creates: /home/docker/nextcloud/env
+        chdir: /symbios/services/nextcloud
+        creates: /symbios/services/nextcloud/env
 
-    - name: /home/docker/nextcloud/fulldockerfile.sh (Download full Dockerfile)
+    - name: /symbios/services/nextcloud/fulldockerfile.sh (Download full Dockerfile)
       blockinfile:
-        path: /home/docker/nextcloud/fulldockerfile.sh
+        path: /symbios/services/nextcloud/fulldockerfile.sh
         create: yes
         mode: 0550
         owner: root
@@ -150,7 +150,7 @@
         marker: "# {mark} ANSIBLE MANAGED BLOCK"
         block: |
           # Change to service directory
-          cd /home/docker/nextcloud
+          cd /symbios/services/nextcloud
 
           # Download current Dockerfile template from Nextcloud repository
           wget -q https://raw.githubusercontent.com/nextcloud/docker/refs/heads/master/Dockerfile-debian.template -O Dockerfile
@@ -161,22 +161,22 @@
         validate: /bin/bash -n %s
       notify: run fulldockerfile.sh
 
-    - name: /home/docker/nextcloud/fulldockerfile.sh shebang
+    - name: /symbios/services/nextcloud/fulldockerfile.sh shebang
       lineinfile:
-        path: /home/docker/nextcloud/fulldockerfile.sh
+        path: /symbios/services/nextcloud/fulldockerfile.sh
         insertbefore: BOF
         line: "#!/bin/bash -e"
 
     - name: Gen initial passwords if not exists
       ansible.builtin.shell: ./fulldockerfile.sh
       args:
-        chdir: /home/docker/nextcloud
-        creates: /home/docker/nextcloud/Dockerfile
+        chdir: /symbios/services/nextcloud
+        creates: /symbios/services/nextcloud/Dockerfile
 
 
-    - name: /home/docker/nextcloud/collabora.genpw.sh (generate Collabora PW)
+    - name: /symbios/services/nextcloud/collabora.genpw.sh (generate Collabora PW)
       blockinfile:
-        path: /home/docker/nextcloud/collabora.genpw.sh
+        path: /symbios/services/nextcloud/collabora.genpw.sh
         create: yes
         mode: 0550
         owner: root
@@ -184,7 +184,7 @@
         marker: "# {mark} ANSIBLE MANAGED BLOCK"
         block: |
           # Change to service directory
-          cd /home/docker/nextcloud
+          cd /symbios/services/nextcloud
 
           # Generate random password for Collabora
           g_collabora_password=$(pwgen -s 32 1)
@@ -205,21 +205,21 @@
         validate: /bin/bash -n %s
       notify: run collabora.genpw.sh
 
-    - name: /home/docker/nextcloud/collabora.genpw.sh shebang
+    - name: /symbios/services/nextcloud/collabora.genpw.sh shebang
       lineinfile:
-        path: /home/docker/nextcloud/collabora.genpw.sh
+        path: /symbios/services/nextcloud/collabora.genpw.sh
         insertbefore: BOF
         line: "#!/bin/bash -e"
 
     - name: Generate Collabora password
       ansible.builtin.shell: ./collabora.genpw.sh
       args:
-        chdir: /home/docker/nextcloud
-        creates: /home/docker/nextcloud/env.collabora
+        chdir: /symbios/services/nextcloud
+        creates: /symbios/services/nextcloud/env.collabora
 
-    - name: /home/docker/nextcloud/remoteip.conf (real IP logging and no Proxy IP)
+    - name: /symbios/services/nextcloud/remoteip.conf (real IP logging and no Proxy IP)
       blockinfile:
-        path: /home/docker/nextcloud/remoteip.conf
+        path: /symbios/services/nextcloud/remoteip.conf
         create: yes
         mode: 0444
         owner: root
@@ -233,9 +233,9 @@
         backup: yes
       notify: Restart nextcloud
 
-    - name: /home/docker/nextcloud/turnserver.conf
+    - name: /symbios/services/nextcloud/turnserver.conf
       blockinfile:
-        path: /home/docker/nextcloud/turnserver.conf
+        path: /symbios/services/nextcloud/turnserver.conf
         mode: "0400"
         owner: root
         group: root
@@ -254,9 +254,9 @@
           no-multicast-peers
         backup: yes
 
-    - name: /home/docker/nextcloud/docker-compose.yml Container Configuration
+    - name: /symbios/services/nextcloud/docker-compose.yml Container Configuration
       blockinfile:
-        path: /home/docker/nextcloud/docker-compose.yml
+        path: /symbios/services/nextcloud/docker-compose.yml
         create: yes
         mode: 0440
         owner: root
@@ -388,9 +388,9 @@
         backup: yes
       notify: Restart nextcloud
 
-    - name: /home/docker/traefik/providers/nextcloud.yml Routing Configuration
+    - name: /symbios/services/traefik/providers/nextcloud.yml Routing Configuration
       blockinfile:
-        path: /home/docker/traefik/providers/nextcloud.yml
+        path: /symbios/services/traefik/providers/nextcloud.yml
         create: yes
         mode: 0444
         owner: root
@@ -457,21 +457,21 @@
 
     - name: Create oidc client secret for Nextcloud
       ansible.builtin.shell: |
-        /home/docker/authelia/gen-oidc-client-secret.sh /home/docker/nextcloud
+        /symbios/services/authelia/gen-oidc-client-secret.sh /symbios/services/nextcloud
       changed_when: false
       failed_when: false
 
     - name: write OIDC config in authelias configuration.yml for Nextcloud
       ansible.builtin.blockinfile:
-        path: /home/docker/authelia/authelia-data/configuration.yml
+        path: /symbios/services/authelia/authelia-data/configuration.yml
         marker: "# {mark} ANSIBLE MANAGED BLOCK OIDC nextcloud"
         block: |2
                 # Nextcloud
                 - client_id: 'nextcloud'
                   client_name: 'Nextcloud'
-                  client_secret: '{{ lookup('file', '/home/docker/nextcloud/oidc_digest') }}'
+                  client_secret: '{{ lookup('file', '/symbios/services/nextcloud/oidc_digest') }}'
                   public: false
-                  authorization_policy: '{{ lookup('file', '/home/docker/authelia/authorization_policy') }}'
+                  authorization_policy: '{{ lookup('file', '/symbios/services/authelia/authorization_policy') }}'
                   redirect_uris:
                     - 'https://nextcloud.{{ base_domain }}/apps/user_oidc/code'
                   scopes:
@@ -494,16 +494,16 @@
     - name: Start nextcloud
       ansible.builtin.shell: docker compose up -d
       args:
-        chdir: /home/docker/nextcloud
-        creates: /home/docker/nextcloud/nextcloud-data/config/config.php
+        chdir: /symbios/services/nextcloud
+        creates: /symbios/services/nextcloud/nextcloud-data/config/config.php
 
     - name: Wait until nextcloud install is finished
       wait_for:
-        path: /home/docker/nextcloud/nextcloud-data/config/config.php
+        path: /symbios/services/nextcloud/nextcloud-data/config/config.php
 
-    - name: /home/docker/nextcloud/nextcloud-data/config/local.config.php (local nextcloud config)
+    - name: /symbios/services/nextcloud/nextcloud-data/config/local.config.php (local nextcloud config)
       blockinfile:
-        path: /home/docker/nextcloud/nextcloud-data/config/local.config.php
+        path: /symbios/services/nextcloud/nextcloud-data/config/local.config.php
         create: yes
         mode: 0444
         owner: root
@@ -521,15 +521,15 @@
           );
         backup: yes
 
-    - name: /home/docker/nextcloud/nextcloud-data/config/local.config.php shebang
+    - name: /symbios/services/nextcloud/nextcloud-data/config/local.config.php shebang
       lineinfile:
-        path: /home/docker/nextcloud/nextcloud-data/config/local.config.php
+        path: /symbios/services/nextcloud/nextcloud-data/config/local.config.php
         insertbefore: BOF
         line: "<?php"
 
-    - name: /home/docker/nextcloud/nextcloud.init.sh
+    - name: /symbios/services/nextcloud/nextcloud.init.sh
       blockinfile:
-        path: /home/docker/nextcloud/nextcloud.init.sh
+        path: /symbios/services/nextcloud/nextcloud.init.sh
         mode: "0500"
         owner: root
         group: root
@@ -541,18 +541,18 @@
           do
             echo "Waiting for Login screen..."
             # restart traefik on Problems with ACME/letsencrypt
-            if [ -f /home/docker/traefik/docker-compose.yml ]
+            if [ -f /symbios/services/traefik/docker-compose.yml ]
             then
-              if docker compose -f /home/docker/traefik/docker-compose.yml logs | grep -E -q "nextcloud.{{ base_domain }}.+error.+acme-challenge"
+              if docker compose -f /symbios/services/traefik/docker-compose.yml logs | grep -E -q "nextcloud.{{ base_domain }}.+error.+acme-challenge"
               then
-                docker compose -f /home/docker/traefik/docker-compose.yml up -d --force-recreate
+                docker compose -f /symbios/services/traefik/docker-compose.yml up -d --force-recreate
               fi
             fi
             sleep 10
           done
 
           # Change to service directory
-          if ! cd /home/docker/nextcloud
+          if ! cd /symbios/services/nextcloud
           then
             exit 1
           fi
@@ -580,9 +580,9 @@
           done
           
           # stun/turn server
-          if [ -s /home/docker/turn/env ]
+          if [ -s /symbios/services/turn/env ]
           then
-            source /home/docker/turn/env
+            source /symbios/services/turn/env
             docker compose exec -T -u www-data nextcloud ./occ talk:turn:add --secret $TURN_SECRET turns turn.{{ base_domain }}:5349 udp,tcp
             docker compose exec -T -u www-data nextcloud ./occ talk:stun:add turn.{{ base_domain }}:5349
             docker compose exec -T -u www-data nextcloud ./occ talk:stun:delete stun.nextcloud.com:443
@@ -604,9 +604,9 @@
           # OIDC via Authelia (user_oidc)
           if ! [ -s app.user_oidc.configured ]
           then
-            if [ -s /home/docker/nextcloud/oidc_password ]
+            if [ -s /symbios/services/nextcloud/oidc_password ]
             then
-              oidc_secret=$(cat /home/docker/nextcloud/oidc_password)
+              oidc_secret=$(cat /symbios/services/nextcloud/oidc_password)
 
               echo "
                 ./occ user_oidc:provider \
@@ -637,9 +637,9 @@
             LDAP_BASE_DN="{{ ldap_basedn }}"
             LDAP_BIND_DN="cn=readuser,${LDAP_BASE_DN}"
 
-            if [ -s /home/docker/ldap/env.openldap ]
+            if [ -s /symbios/services/ldap/env.openldap ]
             then
-              LDAP_PASSWORD=$(grep ^LDAP_READUSER_PASSWORD= /home/docker/ldap/env.openldap | cut -d= -f2-)
+              LDAP_PASSWORD=$(grep ^LDAP_READUSER_PASSWORD= /symbios/services/ldap/env.openldap | cut -d= -f2-)
             fi
 
             docker compose exec -T -u www-data nextcloud ./occ ldap:create-empty-config >>app.user_ldap.configured
@@ -670,10 +670,10 @@
       notify: run nextcloud.init
 
     - name: Run nextcloud.init after install
-      ansible.builtin.shell: bash /home/docker/nextcloud/nextcloud.init.sh
+      ansible.builtin.shell: bash /symbios/services/nextcloud/nextcloud.init.sh
       args:
-        chdir: /home/docker/nextcloud
-        creates: /home/docker/nextcloud/nextcloud.init.log
+        chdir: /symbios/services/nextcloud
+        creates: /symbios/services/nextcloud/nextcloud.init.log
 
     - name: /usr/local/sbin/autoupdate.d/nextcloud.update
       blockinfile:
@@ -685,13 +685,13 @@
         marker: "# {mark} ANSIBLE MANAGED BLOCK"
         block: |
           # Change to service directory or skip update
-          if ! cd /home/docker/nextcloud
+          if ! cd /symbios/services/nextcloud
           then
             continue
           fi
 
           # Update full Dockerfile
-          /home/docker/nextcloud/fulldockerfile.sh
+          /symbios/services/nextcloud/fulldockerfile.sh
           # Nextcloud maintenance and app-update
           docker compose exec -T -u www-data nextcloud ./occ db:add-missing-columns
           docker compose exec -T -u www-data nextcloud ./occ db:add-missing-indices
@@ -705,10 +705,10 @@
           #docker compose exec -T -u www-data nextcloud ./occ maps:scan-photos --now
           docker compose exec -T -u www-data nextcloud ./occ db:convert-filecache-bigint -n
           # define stun/turn server maybe new password
-          if [ -s /home/docker/turn/env ]
+          if [ -s /symbios/services/turn/env ]
           then
              # turn
-             source /home/docker/turn/env
+             source /symbios/services/turn/env
              docker compose exec -T -u www-data nextcloud ./occ talk:turn:delete turns turn.{{ base_domain }}:5349 udp,tcp
              docker compose exec -T -u www-data nextcloud ./occ talk:turn:add --secret $TURN_SECRET turns turn.{{ base_domain }}:5349 udp,tcp
              # stun
@@ -716,9 +716,9 @@
              docker compose exec -T -u www-data nextcloud ./occ talk:stun:add turn.{{ base_domain }}:5349
              docker compose exec -T -u www-data nextcloud ./occ talk:stun:delete stun.nextcloud.com:443
           fi
-          if [ -s /home/docker/nextcloud/nextcloud-data/data/nextcloud.log ]
+          if [ -s /symbios/services/nextcloud/nextcloud-data/data/nextcloud.log ]
           then
-            docker compose -f /home/docker/nextcloud/docker-compose.yml exec -ti -u www-data nextcloud ./occ log:tail 1000 | grep " Error " | grep -v "Can't get app storage," | dd bs=1M count=1 2>/dev/null >"${g_tmp}/nextcloud-error.log"
+            docker compose -f /symbios/services/nextcloud/docker-compose.yml exec -ti -u www-data nextcloud ./occ log:tail 1000 | grep " Error " | grep -v "Can't get app storage," | dd bs=1M count=1 2>/dev/null >"${g_tmp}/nextcloud-error.log"
             if [ -s "${g_tmp}/nextcloud-error.log" ]
             then
               g_echo_error "Errors in Nextcloud Log: $(cat "${g_tmp}/nextcloud-error.log")"
@@ -757,29 +757,29 @@
     - name: run genpw.sh
       ansible.builtin.shell: ./genpw.sh
       args:
-        chdir: /home/docker/nextcloud
+        chdir: /symbios/services/nextcloud
       notify: Restart nextcloud
 
     - name: run fulldockerfile.sh
       ansible.builtin.shell: ./fulldockerfile.sh
       args:
-        chdir: /home/docker/nextcloud
+        chdir: /symbios/services/nextcloud
 
     - name: run nextcloud.update
       ansible.builtin.shell: bash /usr/local/sbin/autoupdate.d/nextcloud.update
 
     - name: run nextcloud.init
-      ansible.builtin.shell: bash /home/docker/nextcloud/nextcloud.init.sh
+      ansible.builtin.shell: bash /symbios/services/nextcloud/nextcloud.init.sh
 
     - name: Restart nextcloud
       ansible.builtin.shell: docker compose up -d --force-recreate
       args:
-        chdir: /home/docker/nextcloud
+        chdir: /symbios/services/nextcloud
 
     - name: run collabora.genpw.sh
       ansible.builtin.shell: ./collabora.genpw.sh
       args:
-        chdir: /home/docker/nextcloud
+        chdir: /symbios/services/nextcloud
       notify: Restart nextcloud
 
     - name: Restart authelia
@@ -789,10 +789,10 @@
           docker compose up -d
         fi
       args:
-        chdir: /home/docker/authelia
+        chdir: /symbios/services/authelia
 
     - name: Restart traefik
       ansible.builtin.shell: docker compose up -d --force-recreate
       args:
-        chdir: /home/docker/traefik
+        chdir: /symbios/services/traefik
 
